In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [5]:
df = pd.read_csv("IsraeliLottery.csv")

In [6]:
df.head()

Game        Date   A   B   C   D   E   F
0  6801  03/09/1968   3  14  18  22  25  33
1  6802  10/09/1968  13  20  23  29  32  34
2  6803  17/09/1968   8  12  26  27  34  38
3  6804  24/09/1968   1  14  17  26  35  39
4  6805  01/10/1968   1   7   8   9  11  30

In [7]:
df.tail()

Game        Date  A   B   C   D   E   F
4042  3467  14/05/2022  9  16  17  21  26  29
4043  3468  17/05/2022  1   4   5  24  31  32
4044  3469  19/05/2022  1   8  18  25  29  30
4045  3470  21/05/2022  3   4   5  15  24  33
4046  3471  24/05/2022  6  10  13  20  23  35

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4047 entries, 0 to 4046
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Game    4047 non-null   int64 
 1   Date    4047 non-null   object
 2   A       4047 non-null   int64 
 3   B       4047 non-null   int64 
 4   C       4047 non-null   int64 
 5   D       4047 non-null   int64 
 6   E       4047 non-null   int64 
 7   F       4047 non-null   int64 
dtypes: int64(7), object(1)
memory usage: 253.1+ KB


In [9]:
df.describe()

Game            A            B            C            D  \
count  4047.000000  4047.000000  4047.000000  4047.000000  4047.000000   
mean   4695.399061     5.698542    11.428713    17.128737    22.948357   
std    3106.179305     4.635402     5.988067     6.698026     6.820599   
min    1035.000000     1.000000     2.000000     3.000000     4.000000   
25%    2046.500000     2.000000     7.000000    12.000000    18.000000   
50%    3058.000000     4.000000    10.000000    17.000000    23.000000   
75%    8011.500000     8.000000    15.000000    22.000000    28.000000   
max    9934.000000    31.000000    37.000000    44.000000    46.000000   

                 E            F  
count  4047.000000  4047.000000  
mean     28.795404    34.635285  
std       6.616360     5.910514  
min       7.000000    13.000000  
25%      24.000000    31.000000  
50%      29.000000    35.000000  
75%      33.000000    38.000000  
max      48.000000    49.000000

In [10]:
df.drop(['Game', 'Date'], axis=1, inplace=True)

In [11]:
df.head()

A   B   C   D   E   F
0   3  14  18  22  25  33
1  13  20  23  29  32  34
2   8  12  26  27  34  38
3   1  14  17  26  35  39
4   1   7   8   9  11  30

In [12]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [13]:
transformed_df.head()

0         1         2         3         4         5
0 -0.582231  0.429455  0.130094 -0.139060 -0.573710 -0.276708
1  1.575345  1.431572  0.876674  0.887369  0.484404 -0.107497
2  0.496557  0.095416  1.324623  0.594104  0.786722  0.569346
3 -1.013746  0.429455 -0.019223  0.447471  0.937882  0.738557
4 -1.013746 -0.739681 -1.363068 -2.045287 -2.689939 -0.784341

In [14]:
# All our games
number_of_rows = df.values.shape[0]
number_of_rows

4047

In [15]:
# Amount of games we need to take into consideration for prediction
window_length = 7
window_length 

7

In [16]:
# Balls counts
number_of_features = df.values.shape[1]
number_of_features

6

In [17]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)
X

array([[[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        ...,
        [2.19987190e-152, 6.01099881e+175, 9.03082937e-090,
         4.82336277e+228, 5.04533095e+223, 2.35567712e+251],
        [1.27640997e-152, 5.04620669e+180, 4.95241270e+223,
         5.71606413e+180, 1.06314419e+248, 9.08367206e+223],
        [1.55541130e+161, 6.32672135e+180, 2.45652619e+198,
         1.27989698e-152, 4.08841057e+233, 5.02065932e+276]],

       [[9.10580156e+102, 1.14503156e+243, 3.68065911e+180,
         1.69375611e+190, 1.99722753e+161, 5.53083643e-311],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.000000

In [18]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)
y

array([[  0.        ,  53.31128703,   5.29670833,  22.07629815,
         22.07629815,   1.69379259],
       [ 22.07629815,  13.67921389,   7.28212963,  13.67921389,
          0.48796111,  13.67921389],
       [  7.28212963,   0.48796111,  10.89962407,  28.10545555,
         39.70837129,   7.28212963],
       ...,
       [  2.67415833,   2.67415833,   2.67415833,  13.21529991,
          5.59187516,   5.59187516],
       [135.37986626,   0.40358754,  13.21529991,   2.67415833,
          0.40358754,   1.86244595],
       [  1.86244595,   5.59187516,  31.7564415 ,   0.40358754,
          1.86244595,   0.40358754]])

In [19]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [20]:
X.shape

(4040, 7, 6)

In [21]:
y.shape

(4040, 6)

In [22]:
X[0]

array([[-0.58223113,  0.429455  ,  0.1300936 , -0.13906023, -0.57371015,
        -0.27670816],
       [ 1.57534546,  1.43157169,  0.87667445,  0.88736948,  0.4844041 ,
        -0.10749723],
       [ 0.49655716,  0.0954161 ,  1.32462296,  0.59410385,  0.78672246,
         0.56934648],
       [-1.01374645,  0.429455  , -0.01922257,  0.44747103,  0.93788164,
         0.7385574 ],
       [-1.01374645, -0.73968114, -1.36306809, -2.04528682, -2.68993865,
        -0.78434094],
       [ 0.2807995 , -0.40564224, -1.06443575, -0.8722243 , -0.87602851,
        -0.10749723],
       [-1.01374645, -0.90670059,  0.87667445,  0.88736948,  0.63556328,
        -0.10749723]])

In [23]:
X[1]

array([[ 1.57534546,  1.43157169,  0.87667445,  0.88736948,  0.4844041 ,
        -0.10749723],
       [ 0.49655716,  0.0954161 ,  1.32462296,  0.59410385,  0.78672246,
         0.56934648],
       [-1.01374645,  0.429455  , -0.01922257,  0.44747103,  0.93788164,
         0.7385574 ],
       [-1.01374645, -0.73968114, -1.36306809, -2.04528682, -2.68993865,
        -0.78434094],
       [ 0.2807995 , -0.40564224, -1.06443575, -0.8722243 , -0.87602851,
        -0.10749723],
       [-1.01374645, -0.90670059,  0.87667445,  0.88736948,  0.63556328,
        -0.10749723],
       [-0.79798879,  0.26243555,  0.42872594,  0.1542054 , -0.57371015,
        -1.29197372]])

In [24]:
y[0]

array([-0.79798879,  0.26243555,  0.42872594,  0.1542054 , -0.57371015,
       -1.29197372])

In [25]:
y[1]

array([-0.58223113, -0.40564224,  1.32462296,  1.32726792,  0.78672246,
        0.23092462])

In [26]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 100

In [27]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(59))
# Adding the last output layer
model.add(Dense(number_of_features))

In [36]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [38]:
model.fit(x=X, y=y, batch_size=100, epochs=300, verbose=2)

Epoch 1/300
41/41 - 12s - loss: 0.0094 - accuracy: 0.9245 - 12s/epoch - 285ms/step
Epoch 2/300
41/41 - 1s - loss: 0.0081 - accuracy: 0.9339 - 637ms/epoch - 16ms/step
Epoch 3/300
41/41 - 1s - loss: 0.0077 - accuracy: 0.9354 - 633ms/epoch - 15ms/step
Epoch 4/300
41/41 - 1s - loss: 0.0072 - accuracy: 0.9401 - 629ms/epoch - 15ms/step
Epoch 5/300
41/41 - 1s - loss: 0.0070 - accuracy: 0.9342 - 644ms/epoch - 16ms/step
Epoch 6/300
41/41 - 1s - loss: 0.0066 - accuracy: 0.9351 - 652ms/epoch - 16ms/step
Epoch 7/300
41/41 - 1s - loss: 0.0067 - accuracy: 0.9349 - 619ms/epoch - 15ms/step
Epoch 8/300
41/41 - 1s - loss: 0.0066 - accuracy: 0.9374 - 638ms/epoch - 16ms/step
Epoch 9/300
41/41 - 1s - loss: 0.0062 - accuracy: 0.9394 - 639ms/epoch - 16ms/step
Epoch 10/300
41/41 - 1s - loss: 0.0061 - accuracy: 0.9391 - 630ms/epoch - 15ms/step
Epoch 11/300
41/41 - 1s - loss: 0.0061 - accuracy: 0.9381 - 637ms/epoch - 16ms/step
Epoch 12/300
41/41 - 1s - loss: 0.0062 - accuracy: 0.9356 - 638ms/epoch - 16ms/step
E

In [39]:
to_predict = df.tail(8)
to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)
to_predict

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


A   B   C   D   E   F
4039   1  14  15  17  28  37
4040   3  13  21  24  27  35
4041  17  19  21  23  25  34
4042   9  16  17  21  26  29
4043   1   4   5  24  31  32
4044   1   8  18  25  29  30
4045   3   4   5  15  24  33

In [40]:
to_predict = np.array(to_predict)
to_predict

array([[ 1, 14, 15, 17, 28, 37],
       [ 3, 13, 21, 24, 27, 35],
       [17, 19, 21, 23, 25, 34],
       [ 9, 16, 17, 21, 26, 29],
       [ 1,  4,  5, 24, 31, 32],
       [ 1,  8, 18, 25, 29, 30],
       [ 3,  4,  5, 15, 24, 33]])

In [41]:
scaled_to_predict = scaler.transform(to_predict)

In [42]:
y_pred = model.predict(np.array([scaled_to_predict]))
print("The predicted numbers in the last lottery game are:", scaler.inverse_transform(y_pred).astype(int)[0])

The predicted numbers in the last lottery game are: [ 5  9 12 20 23 35]


In [43]:
prediction = df.tail(1)
prediction = np.array(prediction)
print("The actual numbers in the last lottery game were:", prediction[0])

The actual numbers in the last lottery game were: [ 6 10 13 20 23 35]
